### ISSUE TITLE
When the user inputs a dot into the sandbox editor vocabErrors positions will be off after the dot.

### ISSUE THREAD

**Issue by TimothyGillespie** [diproche/webinterface#102]
`Die Sonne.` will return a correct index for disallowed the vocabulary of "Die" and "Sonne", but if there is something afterwards like `Die Sonne. Die Sonne.` The second "Die" and "Sonne" will not be indexed correctly.
Eventually the same with different punctuation symbols too?

**Comment by Korosensei42** [comment]
Indeed, it seems like currently only symbols that count towards a word count. This means for example, that all word barriers get ignored when trying to index the issues. Gonna try to fix that tomorrow.

**Comment by Korosensei42** [comment]
Solved by #106
