### ISSUE TITLE
Make notation in exercises and examples uniform

### ISSUE THREAD

**Issue by Korosensei42** [diproche/webinterface#113]
Currently, for the examples there is mixed notation. I.e.
sometimes there are $-signs around formulas and sometimes there are not. 
Additionally the reader might be confused when encountering them, since it might
feel unnatural for non-LaTeX-conform people. So all examples and exercises
should not contain $-signs.

**Comment by TimothyGillespie** [comment]
Why should the examples not contain the $ if they were needed as of now to insert it properly? The currently rule is any non atomic formula has to be entered with $.

**Comment by Korosensei42** [comment]
Is it? In that case, I remembered this exactly the wrong way. However, in this case I will add $ to each formula, even the atomic ones, to keep it consistent for the user.

**Comment by TimothyGillespie** [comment]
It should be. As of now I cannot check it since I have no computer available to me. I am not sure if an atomic formula can be in $ but I would think it should be no issue.

What you probably remembered is our aim to eventually get it to not need the delimiter.

**Comment by Korosensei42** [comment]
That's likely.
