### ISSUE TITLE
Fill the main page with content

### ISSUE THREAD

**Issue by Korosensei42** [diproche/webinterface#115]
Currently the main page is empty. The goal is to fill it with information about Diproche and the interface.

Some points that should be agreed upon include:
- Should the user be adressed directly via "Du", or only
indirectly via "man"?
- Should the philosophy / thought behind Diproche be mentioned or only the functionality?
- Should the text contain some kind of motivation for the reader? I.e. telling them why Diproche might help them?

**Comment by TimothyGillespie** [comment]
My opinion would be:
- The user should be addressed more professionally or indirectly so "man". "Du" is more "dangerous" and inflexible.
- Can be mentioned briefly I would think, but going into length about it should have an own page. Different content should have different headings.
- Don't see an issue with that. This should imo have an own heading too then. At the same time we don't need to advertise ourselves specifically like a company.

**Comment by TimothyGillespie** [comment]
Solved by #116
