### ISSUE TITLE
Create the Pre-Processing to Prolog Pipeline 

### ISSUE THREAD

**Issue by TimothyGillespie** [diproche/webinterface#14]
All the different functionalities (error detection, issue handling, text to prolog readable list, prolog interpreter) need to be connected.to a coherent system of forwarded and partially processed data with respective returns and feedback.

Possible Idea:
Vocabulary Error Detection -> Syntax Error Detection and Text To Prolog Readable List (text formatter) -> Issue Handler -> Prolog Interpreter.

**Comment by Korosensei42** [comment]
For this Issue I would like to sketch my idea of how the pipeline should work alongside an example first.

Input: Text from User as a String. Example: "This text has a wrongWord and it holds that 2 += 2 5" where "wrongWord" is a wrong word.
**1) Vocabulary Error Detection:**
Tell the User, that "wrongWord" is not allowed and where "wrongWord" is. This can for example happen by highlighting "wrongWord" in the input.

Optimally: Make a suggestion for a replacement. However, this is not possible yet (later task for improving the vocabChecker)

Right now: Just let the User try things out until he has an accepted word.

Output: A String that consists only of allowed words. Example: "This text has a rightWord and it holds that 2 += 2 5"

**2) Syntax Error Detection**
Tell the User, that "2 += 2 5" is syntactically incorrect.

Optimally: Make a suggestion for improvement. However, I don't know if that is possible right now. Might have to wait.

Right now: Most likely treat it the same way as in step 1).

Output: A String consisting of syntactically correct expressions. Example: "This text has a rightWord and it holds that 2 + 2 = 5". 

Now, for the case that the user instead adds a new wrong word, start the pipeline at Step 1) again. Now with this output.

**3) Text to Prolog Readable List**
Take the String from before and transform it into a list.

Example: "[This, text, has, a, rightWord, and, it, holds, that, =[+[2,2],5]]].".

Output: List mentioned above.

**4) Issue Handler**
Tell the User what is still wrong. Most likely the remaining errors will be on a semantic level.

Ideally: Propose a specific solution to the user.

Right now: Just tell the user where his mistake is.

Example: Tell the User that "2 + 2 = 5" in his original text is semantically wrong and tell him where in his text this statement is. Wait for him to change "5" to "4". 

Now, it is possible that the user adds new wrong vocabulary or new wrong syntax. For this: Start the whole pipeline with the new input again at Step 1).

**5) Prolog Interpreter**
Tell the User that "This text has a rightWord" does not contribute to his second statement of "2 + 2 = 4", but that the statement is semantically correct.

**Comment by Khazuar** [comment]
@Korosensei42 Looks good. I doubt it will be easy though to determine a useful issue-free version of the user-input in each step. We might have to abort the pipeline in case of "critical issues" and return the user all issues found so far.
