### ISSUE TITLE
Convert text to Prolog readable lists

### ISSUE THREAD

**Issue by TimothyGillespie** [diproche/webinterface#2]
This task is about preparing the user input (a `string` from a text input) to the prolog-preferred list-data format. The result should be a module (own ts-file) that includes a function `export function textToListFormat(input: text): Array<any>`.

The input needs to be split according to paragraphs, sentences and words. So: [_sentence_, _sentence_, [abs], _sentence_ ...], where each _sentence_ is like [_word_, _word_ ...]. Paragraph-breaks should be denoted as literally `[abs]`. No punctuation should survive the transformation.  
Mathematical expressions need to be included in their own list format. We will use `$`-delimiters to separate expressions from the rest of the text like this: `We prove that $5+6=11$.`. The list format for expressions works as follows:
For `A` and `B` being formulas, `[A,->,B]`, `[A,<->,B]`, `[A,and,B]`, `[A,or,B]`, `[neg,A]`, `[all,X,A]`, `[ex,X,A]`, `[all,[X,in,T],A]`, `[ex,[X,in,T],A]` are formulas as well.
If `p` is a predicate with _n_ arguments and `x1`...`xn` are terms, then `[p, [x1...xn]]` is a formula.
If `f` is a function with _n_ arguments and `x1`...`xn` are terms, then `[f, [x1...xn]]` is a term.
Variables and constants are terms. 

So if `$5+6=11$` appears in the text it should become `[[+, [5, 6]],=,11]`. There should be a separate function in your module that turns these expression-texts to lists, like `export function expressionTextToListFormat(text: string): Array<any>`. Tip: Don't bother too much with arithmetic operator precedence for now.

There should be test-cases for both methods that cover a few "normal" examples and the edge-cases in a separate `.test.ts`-file. See the [JEST](https://jestjs.io/docs/en/getting-started)-documentation for details.

**Comment by Khazuar** [comment]
This task is not just about converting math expressions, but text in general (including the math expressions within).

**Comment by Khazuar** [comment]
@Korosensei42 According to the latest Email by Frau Krapf the input to Merlins code *needs* to be in the list-format, so this is a proper task again.

**Comment by Korosensei42** [comment]
@Khazuar Okay, in that case I misunderstood what his code is capable of. I will get to this issue tomorrow
or friday. Maybe I write the tests for the other function I wrote before this issue, but most definitely this issue has a bigger priority now.

**Comment by RonjaKaehne** [comment]
"So if $5+6=11$ appears in the text it should become [[+, [5, 6]],=,11]. There should be a separate function in your module that turns these expression-texts to lists, like export function expressionTextToListFormat(text: string): Array<any>. Tip: Don't bother too much with arithmetic operator precedence for now."
removed to another playground. the rest works
