### ISSUE TITLE
Fix indexing for vocabErrors

### ISSUE THREAD

**Issue by Korosensei42** [diproche/webinterface#50]
Currently inputs like `$sonne und sonne$` create a duplicate of just a single issue, namely
```
Das Wort 'sonne' in der Eingabe ist nicht erlaubt.
Von Index 1 bis 6
Das Wort 'sonne' in der Eingabe ist nicht erlaubt.
Von Index 1 bis 6
```

This should be fixed, meaning it should return issues in the form of
```
Das Wort 'sonne' in der Eingabe ist nicht erlaubt.
Von Index 1 bis 5 und von Index 11 bis 15
```

**Comment by Korosensei42** [comment]
@TimothyGillespie @RonjaKaehne This bug is currently not visible on master, since we didn't push an update regarding the GUI to this branch recently. In which of your branches is this bug visibly present?

**Comment by TimothyGillespie** [comment]
It is reproducable on master for me. What Browser are you using and what Operating System?

**Comment by Korosensei42** [comment]
I am using Firefox on Windows 10

**Comment by TimothyGillespie** [comment]
Hmm that's the same as mine. Did you git pull?

**Comment by Korosensei42** [comment]
I think I did so, but I will try it again.

**Comment by Korosensei42** [comment]
Okay, it works now. I don't know why it didn't earlier. Maybe I really forgot to pull, even though I was certain I did so

**Comment by Korosensei42** [comment]
A partial fix is available in #74

**Comment by TimothyGillespie** [comment]
This should be completely solved now with #74 as far as I can see?

**Comment by Korosensei42** [comment]
This is indeed solved, yes. Thanks for closing it. Forgot about that

**Comment by RonjaKaehne** [comment]
we still got a bug here but another one now:
for example:
ffff ff
returns the following issues:
Das Wort 'ffff' in der Eingabe ist nicht erlaubt.
Von Index 0 bis 4
Das Wort 'ff' in der Eingabe ist nicht erlaubt.
Von Index 0 bis 2
Das Wort 'ff' in der Eingabe ist nicht erlaubt.
Von Index 1 bis 3
Das Wort 'ff' in der Eingabe ist nicht erlaubt.
Von Index 2 bis 4
Das Wort 'ff' in der Eingabe ist nicht erlaubt.
Von Index 5 bis 7

But only the first and the last issue should get collected here

**Comment by RonjaKaehne** [comment]
i guess we can catch this if we search for white spaces between words first.
