### ISSUE TITLE
Finishing the menu

### ISSUE THREAD

**Issue by Korosensei42** [diproche/webinterface#57]
Currently only some dummy-buttons are present. The following points should be decided:

- what belongs in the menu?
- what kind of menu should it be?
- if submenus are present, how and were should they be?
- what are intuitive names? I.e.: Choose names that actually tell the user what to expect when clicking on the buttons/menupoints and correspond to what is behind the button/menupoint

**Comment by RonjaKaehne** [comment]
I build a top navigation bar with a dropdownmenu to select between the future and present content. The actual menu can be modified later but the elements works well for the actual version of our app.
