### ISSUE TITLE
Adding a textbox with autosize

### ISSUE THREAD

**Issue by RonjaKaehne** [diproche/webinterface#69]
The input textbox for the profchecker should automaticly growing if it's needed.

**Comment by TimothyGillespie** [comment]
This issue will very likely be solved by my adjustments as a by product since moving from a textarea to an editable div seems the most practical.

**Comment by RonjaKaehne** [comment]
okay then i assign this issue to you.

**Comment by TimothyGillespie** [comment]
Pretty much solved with #75 automatically.
