### ISSUE TITLE
implement examples

### ISSUE THREAD

**Issue by RonjaKaehne** [diproche/webinterface#70]
Actually we just have an empty inputtextbox. if someone wants to exercise with our tool it would be nice to have the possibilty to see an example how it works or where he can do some simple exercises. You can call it tutorial if u want. Anyway if we would try to implement this we also got some testcases for us too. You also can add some input advices in this section for the user, for example that we recommend use a explicit writing style.
What do you think about this?

**Comment by Korosensei42** [comment]
I think this is a good idea!
In the very end I woulld suggest that we have a different tutorial for every Spielwiese. But for the start one tutorial for Aussagenlogik should be fine.

**Comment by RonjaKaehne** [comment]
good advice. i open 2 other issues and rename this one into example

**Comment by Korosensei42** [comment]
> good advice. i open 2 other issues and rename this one into example

This reminds me of another possibility. We could go ahead and write up a technical glossary explaining all terms. That will be useful in case other developers continue this project later.

**Comment by TimothyGillespie** [comment]
Solved by #100
