### ISSUE TITLE
implement a user wiki for propositional logic

### ISSUE THREAD

**Issue by RonjaKaehne** [diproche/webinterface#81]
We should think about the content we want to collect inside a inner wiki for every "spielwiese".
This a possible suggestions:
step 1:
- adding references or links to basic literature for propositional logic.
- adding own references for the theory
- adding a reference list for allowed input
- adding a recommended writing style
- (u can make other suggestions here)
.....
step 2:
implementation

**Comment by Korosensei42** [comment]
Solved by #106
